CREATE TABLE SHOWROOM_LIST
(
  SHOWROOM_ID INT(11) PRIMARY KEY NOT NULL auto_increment,
  MANAGER     VARCHAR(255),
  LOCATION    VARCHAR(255)
);

CREATE TABLE CARS_LIST
(
  CAR_ID      INT(11) PRIMARY KEY NOT NULL auto_increment,
  NAME        VARCHAR(255),
  COLOR       VARCHAR(255),
  SHOWROOM_ID INT(11),
  CAR_INDEX   INT(11),
  CONSTRAINT FK2fplr828hidk3m54lkcqhrf39 FOREIGN KEY (SHOWROOM_ID) REFERENCES SHOWROOM_LIST (SHOWROOM_ID)
);
CREATE INDEX FK2fplr828hidk3m54lkcqhrf39 ON CARS_LIST (SHOWROOM_ID);